version: '2.1'
services:
  shell:
    build: .
    env_file: .env
    volumes:
      - ./scripts:/scripts:ro
      - .:/opt/app:rw
    working_dir: /opt/app
    command: bash

  rancher:
    image: amaysim/rancher-utils:1.2.5
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: ${DOCKER_COMPOSE_IP_RANGE}