version: '2.1'
services:
  shell:
    image: amaysim/rancher-utils:1.0.0
    command: shell
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: bash

  # deploy is an example of deploying a docker image to rancher
  deploy:
    image: amaysim/rancher-utils:1.0.0
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: make -f /scripts/Makefile deploy

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: ${DOCKER_COMPOSE_IP_RANGE}